[module]
  vendor = true
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

[params]
  goToTop = true

name = "Hugo blog awesome"
license = "MIT"

baseURL = "http://example.org/"
languageCode = "en-us"
title = "Yolo Notes"

# theme = "hugo-blog-awesome"

[[params.socialIcons]]
name = "github"
url = "https://github.com/yoloyolo8"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/0xyolo"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"

[params]
  goToTop = true
  toc = true # set to false to disable table of contents 'globally'

# Enable emojis globally
enableEmoji = true


[menu]
  [[menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30


[params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Yolo Notes"
  name = "Yolo"
  description = "我的个人笔记，读书|代码|写字"

[tableOfContents]
startLevel = 2 # ToC starts from H2
endLevel = 4 # ToC ends at H4
ordered = false # generates <ul> instead of <ol>